---
- name: Aplicar Controles CIS
  hosts: web
  become: true
  tags:
    - cis
  vars:
      var_system_crypto_policy: "DEFAULT"
  tasks:
    - block:
        - name: Build and Test AIDE Database - Ensure AIDE Is Installed
          ansible.builtin.package:
            name: aide
            state: present

        - name: Build and Test AIDE Database - Build and Test AIDE Database
          ansible.builtin.command: /usr/sbin/aide --init
          changed_when: true

        - name: Build and Test AIDE Database - Check Whether the Stock AIDE Database Exists
          ansible.builtin.stat:
            path: /var/lib/aide/aide.db.new.gz
          register: aide_database_stat

        - name: Build and Test AIDE Database - Stage AIDE Database
          ansible.builtin.copy:
            src: /var/lib/aide/aide.db.new.gz
            dest: /var/lib/aide/aide.db.gz
            backup: true
            remote_src: true

        - name: Set audit_tools fact
          set_fact:
            audit_tools:
            - /usr/sbin/auditctl
            - /usr/sbin/auditd
            - /usr/sbin/augenrules
            - /usr/sbin/aureport
            - /usr/sbin/ausearch
            - /usr/sbin/autrace
            - /usr/sbin/rsyslogd

        - name: Ensure existing AIDE configuration for audit tools are correct
          ansible.builtin.lineinfile:
            path: /etc/aide.conf
            regexp: ^{{ item }}\s
            line: '{{ item }} p+i+n+u+g+s+b+acl+xattrs+sha512'
          with_items: '{{ audit_tools }}'

        - name: Configure AIDE to properly protect audit tools
          ansible.builtin.lineinfile:
            path: /etc/aide.conf
            line: '{{ item }} p+i+n+u+g+s+b+acl+xattrs+sha512'
          with_items: '{{ audit_tools }}'
        - name: Set cron package name - RedHat
          set_fact:
            cron_pkg_name: cronie
        - name: Set cron package name - Debian
          set_fact:
            cron_pkg_name: cron
        - name: Install cron
          ansible.builtin.package:
            name: '{{ cron_pkg_name }}'
            state: present
        - name: Configure Periodic Execution of AIDE
          ansible.builtin.cron:
            name: run AIDE check
            minute: 5
            hour: 4
            weekday: 0
            user: root
            job: /usr/sbin/aide --check
      tags:
        - aide

    - block:
        - name: Configure System Cryptography Policy
          ansible.builtin.lineinfile:
            path: /etc/crypto-policies/config
            regexp: ^(?!#)(\S+)$
            line: '{{ var_system_crypto_policy }}'
            create: true

        - name: Verify that Crypto Policy is Set (runtime)
          ansible.builtin.command:
            cmd: /usr/bin/update-crypto-policies --set {{ var_system_crypto_policy }}
      tags:
        -  cryptography
    - block:
        - name: Configure SSH to use System Crypto Policy
          ansible.builtin.lineinfile:
            dest: /etc/sysconfig/sshd
            state: absent
            regexp: (?i)^\s*CRYPTO_POLICY.*$
      tags:
        - ssh
